/**
 * Postgres peer DDL bodies for {@link platformMultiDialectMigrations}.
 *
 * Mechanical map from mssql registry peers: TEXT / TIMESTAMPTZ / BYTEA /
 * INT / BIGINT / DOUBLE PRECISION, IDENTITY → GENERATED BY DEFAULT AS IDENTITY,
 * no dbo schema, CREATE TABLE/INDEX IF NOT EXISTS.
 */

/** Postgres batch executor bound by the adapter (pool client or transaction). */
export type PostgresMigrationExecutor = {
  query: (sqlText: string) => Promise<unknown>
}

export async function postgresExec(executor: unknown, sqlText: string): Promise<void> {
  const ex = executor as PostgresMigrationExecutor
  await ex.query(sqlText)
}

export const postgresMigrationSql: Record<number, string> = {
  1: `
CREATE TABLE IF NOT EXISTS users (
  upn            TEXT          NOT NULL CONSTRAINT PK_users PRIMARY KEY,
  username       TEXT          NULL,
  display_name   TEXT          NOT NULL,
  is_admin       INT           NOT NULL DEFAULT 0,
  password_hash  TEXT          NULL,
  source         TEXT          NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL,
  last_login_at  TIMESTAMPTZ   NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  sid           TEXT          NOT NULL CONSTRAINT PK_sessions PRIMARY KEY,
  upn           TEXT          NOT NULL
    CONSTRAINT FK_sessions_users REFERENCES users(upn) ON DELETE CASCADE,
  ip            TEXT          NULL,
  user_agent    TEXT          NULL,
  created_at    TIMESTAMPTZ   NOT NULL,
  last_seen_at  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_sessions_upn ON sessions(upn, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS llm_config (
  id          INT           NOT NULL CONSTRAINT PK_llm_config PRIMARY KEY,
  provider    TEXT          NOT NULL,
  model       TEXT          NOT NULL,
  api_key     TEXT          NOT NULL,
  base_url    TEXT          NOT NULL,
  updated_at  TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS connectors (
  id          TEXT          NOT NULL CONSTRAINT PK_connectors PRIMARY KEY,
  kind        TEXT          NOT NULL,
  body_json   TEXT          NOT NULL,
  enabled     INT           NOT NULL DEFAULT 1,
  created_at  TIMESTAMPTZ   NOT NULL,
  updated_at  TIMESTAMPTZ   NOT NULL,
  updated_by  TEXT          NULL
);
`,

  2: `
CREATE TABLE IF NOT EXISTS threads (
  id           TEXT          NOT NULL CONSTRAINT PK_threads PRIMARY KEY,
  upn          TEXT          NOT NULL
    CONSTRAINT FK_threads_users REFERENCES users(upn),
  title        TEXT          NOT NULL DEFAULT 'New thread',
  created_at   TIMESTAMPTZ   NOT NULL,
  updated_at   TIMESTAMPTZ   NOT NULL,
  archived_at  TIMESTAMPTZ   NULL,
  pinned       INT           NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS IX_threads_upn_updated ON threads(upn, updated_at DESC);

CREATE TABLE IF NOT EXISTS runs (
  id             TEXT          NOT NULL CONSTRAINT PK_runs PRIMARY KEY,
  goal           TEXT          NOT NULL,
  status         TEXT          NOT NULL DEFAULT 'pending',
  answer         TEXT          NULL,
  step_count     INT           NOT NULL DEFAULT 0,
  error          TEXT          NULL,
  parent_run_id  TEXT          NULL,
  thread_id      TEXT          NULL
    CONSTRAINT FK_runs_threads REFERENCES threads(id),
  upn            TEXT          NOT NULL
    CONSTRAINT FK_runs_users REFERENCES users(upn),
  display_name   TEXT          NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL,
  completed_at   TIMESTAMPTZ   NULL
);
CREATE INDEX IF NOT EXISTS IX_runs_upn ON runs(upn, created_at DESC);
CREATE INDEX IF NOT EXISTS IX_runs_parent ON runs(parent_run_id);

CREATE TABLE IF NOT EXISTS token_usage (
  run_id            TEXT          NOT NULL CONSTRAINT PK_token_usage PRIMARY KEY
    CONSTRAINT FK_token_usage_runs REFERENCES runs(id) ON DELETE CASCADE,
  prompt_tokens     INT           NOT NULL DEFAULT 0,
  completion_tokens INT           NOT NULL DEFAULT 0,
  total_tokens      INT           NOT NULL DEFAULT 0,
  llm_calls         INT           NOT NULL DEFAULT 0,
  model             TEXT          NOT NULL DEFAULT 'gpt-5.4',
  created_at        TIMESTAMPTZ   NOT NULL
);
`,

  3: `
CREATE TABLE IF NOT EXISTS event_log (
  id          INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_event_log PRIMARY KEY,
  type        TEXT          NOT NULL,
  data        TEXT          NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL,
  actor_upn   TEXT          NULL,
  run_id      TEXT          NULL,
  plan_id     TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_event_log_time ON event_log(created_at DESC);
CREATE INDEX IF NOT EXISTS IX_event_log_run_id ON event_log(run_id);

CREATE TABLE IF NOT EXISTS audit_log (
  id          INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_audit_log PRIMARY KEY,
  run_id      TEXT          NULL,
  scope_type  TEXT          NOT NULL DEFAULT 'run',
  scope_id    TEXT          NULL,
  actor       TEXT          NOT NULL,
  action      TEXT          NOT NULL,
  detail      TEXT          NOT NULL DEFAULT '{}',
  timestamp   TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_audit_log_run ON audit_log(run_id);

CREATE TABLE IF NOT EXISTS checkpoints (
  run_id       TEXT          NOT NULL CONSTRAINT PK_checkpoints PRIMARY KEY
    CONSTRAINT FK_checkpoints_runs REFERENCES runs(id) ON DELETE CASCADE,
  messages     TEXT          NOT NULL,
  iteration    INT           NOT NULL DEFAULT 0,
  step_counter INT           NOT NULL DEFAULT 0,
  updated_at   TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS sync_environments (
  name        TEXT          NOT NULL CONSTRAINT PK_sync_environments PRIMARY KEY,
  body_json   TEXT          NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL,
  updated_at  TIMESTAMPTZ   NOT NULL,
  updated_by  TEXT          NULL
);

CREATE TABLE IF NOT EXISTS layout_configs (
  id          TEXT          NOT NULL CONSTRAINT PK_layout_configs PRIMARY KEY,
  name        TEXT          NOT NULL,
  config      TEXT          NOT NULL,
  updated_at  TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS policy_configs (
  name        TEXT          NOT NULL CONSTRAINT PK_policy_configs PRIMARY KEY,
  effect      TEXT          NOT NULL,
  condition   TEXT          NOT NULL,
  parameters  TEXT          NOT NULL DEFAULT '{}',
  source      TEXT          NOT NULL DEFAULT 'db',
  created_at  TIMESTAMPTZ   NOT NULL,
  updated_at  TIMESTAMPTZ   NULL,
  updated_by  TEXT          NULL
);

CREATE TABLE IF NOT EXISTS sync_tool_approvals (
  id            TEXT          NOT NULL CONSTRAINT PK_sync_tool_approvals PRIMARY KEY,
  actor_upn     TEXT          NOT NULL,
  tool_name     TEXT          NOT NULL,
  args_json     TEXT          NOT NULL,
  args_key      TEXT          NOT NULL,
  reason        TEXT          NOT NULL,
  policy_name   TEXT          NOT NULL,
  status        TEXT          NOT NULL,
  requested_at  TIMESTAMPTZ   NOT NULL,
  resolved_at   TIMESTAMPTZ   NULL,
  resolved_by   TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_tool_approvals_actor
  ON sync_tool_approvals(actor_upn, tool_name, status);

CREATE TABLE IF NOT EXISTS sync_evidence_log (
  id             TEXT          NOT NULL CONSTRAINT PK_sync_evidence_log PRIMARY KEY,
  tenant_id      TEXT          NOT NULL,
  plan_id        TEXT          NOT NULL,
  proposal_id    TEXT          NULL,
  envelope_path  TEXT          NOT NULL,
  pdf_path       TEXT          NULL,
  content_hash   TEXT          NOT NULL,
  signature_alg  TEXT          NOT NULL,
  signer_id      TEXT          NOT NULL,
  signature      TEXT          NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_sync_evidence_log_plan ON sync_evidence_log(tenant_id, plan_id);
`,

  4: `
CREATE TABLE IF NOT EXISTS sync_phases (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  label            TEXT          NOT NULL,
  sort_order       INT           NOT NULL DEFAULT 0,
  built_in         INT           NOT NULL DEFAULT 0,
  definition_json  TEXT          NOT NULL DEFAULT '{}',
  CONSTRAINT PK_sync_phases PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS sync_actions (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  label            TEXT          NOT NULL,
  built_in         INT           NOT NULL DEFAULT 0,
  definition_json  TEXT          NOT NULL DEFAULT '{}',
  CONSTRAINT PK_sync_actions PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS sync_flows (
  tenant_id     TEXT          NOT NULL,
  id            TEXT          NOT NULL,
  label         TEXT          NOT NULL,
  description   TEXT          NOT NULL DEFAULT '',
  steps_json    TEXT          NOT NULL DEFAULT '[]',
  built_in      INT           NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ   NOT NULL,
  updated_by    TEXT          NULL,
  CONSTRAINT PK_sync_flows PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS sync_value_sources (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  label            TEXT          NOT NULL,
  built_in         INT           NOT NULL DEFAULT 0,
  definition_json  TEXT          NOT NULL DEFAULT '{}',
  CONSTRAINT PK_sync_value_sources PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS sync_publish_meta (
  tenant_id          TEXT          NOT NULL CONSTRAINT PK_sync_publish_meta PRIMARY KEY,
  published_at       TIMESTAMPTZ   NOT NULL,
  published_version  TEXT          NOT NULL,
  catalog_version    INT           NULL
);

CREATE TABLE IF NOT EXISTS sync_definitions (
  tenant_id          TEXT          NOT NULL,
  entity_id          TEXT          NOT NULL,
  definition_json    TEXT          NOT NULL,
  published_at       TIMESTAMPTZ   NULL,
  published_version  TEXT          NULL,
  CONSTRAINT PK_sync_definitions PRIMARY KEY (tenant_id, entity_id)
);

CREATE TABLE IF NOT EXISTS sync_runs (
  plan_id              TEXT             NOT NULL CONSTRAINT PK_sync_runs PRIMARY KEY,
  entity_type          TEXT             NOT NULL,
  entity_id            TEXT             NOT NULL,
  entity_display_name  TEXT             NULL,
  source               TEXT             NOT NULL,
  target               TEXT             NOT NULL,
  actor_upn            TEXT             NOT NULL
    CONSTRAINT FK_sync_runs_users REFERENCES users(upn),
  preview_inserts      INT              NOT NULL DEFAULT 0,
  preview_updates      INT              NOT NULL DEFAULT 0,
  preview_deletes      INT              NOT NULL DEFAULT 0,
  executed_inserts     INT              NULL,
  executed_updates     INT              NULL,
  executed_deletes     INT              NULL,
  preview_totals_json  TEXT             NOT NULL,
  execute_totals_json  TEXT             NULL,
  plan_json            TEXT             NULL,
  status               TEXT             NOT NULL,
  error                TEXT             NULL,
  drift_detected_pct   DOUBLE PRECISION NULL,
  started_at           TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  finished_at          TIMESTAMPTZ      NULL,
  duration_ms          INT              NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_runs_started ON sync_runs(started_at DESC);

CREATE TABLE IF NOT EXISTS sync_audit (
  id         INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_sync_audit PRIMARY KEY,
  plan_id    TEXT          NOT NULL
    CONSTRAINT FK_sync_audit_runs REFERENCES sync_runs(plan_id) ON DELETE CASCADE,
  actor      TEXT          NOT NULL,
  actor_upn  TEXT          NULL,
  action     TEXT          NOT NULL,
  detail     TEXT          NOT NULL DEFAULT '{}',
  timestamp  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_audit_plan ON sync_audit(plan_id);

CREATE TABLE IF NOT EXISTS entity_active (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  current_version  INT           NOT NULL,
  retired_at       TIMESTAMPTZ   NULL,
  CONSTRAINT PK_entity_active PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS entity_versions (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  version          INT           NOT NULL,
  body_json        TEXT          NOT NULL,
  version_label    TEXT          NULL,
  created_by       TEXT          NOT NULL,
  created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  reason           TEXT          NOT NULL DEFAULT '',
  diff_json        TEXT          NOT NULL DEFAULT '[]',
  CONSTRAINT PK_entity_versions PRIMARY KEY (tenant_id, id, version)
);

CREATE TABLE IF NOT EXISTS attachments (
  id               TEXT          NOT NULL CONSTRAINT PK_attachments PRIMARY KEY,
  scope            TEXT          NOT NULL,
  run_id           TEXT          NULL,
  owner_upn        TEXT          NULL,
  original_name    TEXT          NOT NULL,
  normalized_name  TEXT          NOT NULL,
  media_type       TEXT          NOT NULL,
  size_bytes       BIGINT        NOT NULL,
  content_hash     TEXT          NOT NULL,
  storage_uri      TEXT          NOT NULL,
  text_extract_uri TEXT          NULL,
  ingestion_mode   TEXT          NOT NULL,
  status           TEXT          NOT NULL DEFAULT 'uploaded',
  source           TEXT          NOT NULL DEFAULT 'user_upload',
  purpose_tag      TEXT          NULL,
  goal_snapshot    TEXT          NULL,
  uploaded_at      TIMESTAMPTZ   NOT NULL,
  processed_at     TIMESTAMPTZ   NULL,
  retention_until  TIMESTAMPTZ   NULL
);
CREATE INDEX IF NOT EXISTS IX_attachments_run ON attachments(run_id);
CREATE INDEX IF NOT EXISTS IX_attachments_owner ON attachments(owner_upn);

CREATE TABLE IF NOT EXISTS attachment_tags (
  attachment_id TEXT          NOT NULL
    CONSTRAINT FK_attachment_tags_attachments REFERENCES attachments(id) ON DELETE CASCADE,
  tag_key       TEXT          NOT NULL,
  tag_value     TEXT          NOT NULL,
  CONSTRAINT PK_attachment_tags PRIMARY KEY (attachment_id, tag_key, tag_value)
);

CREATE TABLE IF NOT EXISTS attachment_imports (
  id                    TEXT          NOT NULL CONSTRAINT PK_attachment_imports PRIMARY KEY,
  attachment_id         TEXT          NOT NULL
    CONSTRAINT FK_attachment_imports_attachments REFERENCES attachments(id) ON DELETE CASCADE,
  run_id                TEXT          NOT NULL,
  sandbox_path          TEXT          NOT NULL,
  import_mode           TEXT          NOT NULL,
  imported_at           TIMESTAMPTZ   NOT NULL,
  imported_by_tool_call TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_attachment_imports_run ON attachment_imports(run_id);
`,

  5: `
CREATE TABLE IF NOT EXISTS run_log (
  id         INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_run_log PRIMARY KEY,
  run_id     TEXT          NOT NULL
    CONSTRAINT FK_run_log_runs REFERENCES runs(id) ON DELETE CASCADE,
  level      TEXT          NOT NULL DEFAULT 'info',
  message    TEXT          NOT NULL,
  timestamp  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_run_log_run ON run_log(run_id);

CREATE TABLE IF NOT EXISTS trace_entries (
  id          INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_trace_entries PRIMARY KEY,
  run_id      TEXT          NOT NULL
    CONSTRAINT FK_trace_entries_runs REFERENCES runs(id) ON DELETE CASCADE,
  seq         INT           NOT NULL DEFAULT 0,
  data        TEXT          NOT NULL,
  created_at  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_trace_entries_run ON trace_entries(run_id, seq);

CREATE TABLE IF NOT EXISTS run_tool_approvals (
  id            TEXT          NOT NULL CONSTRAINT PK_run_tool_approvals PRIMARY KEY,
  run_id        TEXT          NOT NULL,
  step_id       TEXT          NOT NULL,
  tool_name     TEXT          NOT NULL,
  args_json     TEXT          NOT NULL,
  reason        TEXT          NOT NULL,
  policy_name   TEXT          NOT NULL,
  status        TEXT          NOT NULL,
  requested_at  TIMESTAMPTZ   NOT NULL,
  resolved_at   TIMESTAMPTZ   NULL,
  resolved_by   TEXT          NULL,
  CONSTRAINT UQ_run_tool_approvals_run_step UNIQUE (run_id, step_id)
);
CREATE INDEX IF NOT EXISTS IX_run_tool_approvals_run ON run_tool_approvals(run_id, status);

CREATE TABLE IF NOT EXISTS tool_results (
  id            INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_tool_results PRIMARY KEY,
  run_id        TEXT          NOT NULL
    CONSTRAINT FK_tool_results_runs REFERENCES runs(id) ON DELETE CASCADE,
  tool_call_id  TEXT          NOT NULL,
  tool_name     TEXT          NOT NULL,
  args_json     TEXT          NOT NULL DEFAULT '{}',
  result_json   TEXT          NOT NULL,
  row_count     INT           NULL,
  bytes         INT           NOT NULL DEFAULT 0,
  truncated     INT           NOT NULL DEFAULT 0,
  goal_excerpt  TEXT          NULL,
  created_at    TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_tool_results_run ON tool_results(run_id);

CREATE TABLE IF NOT EXISTS agent_messages (
  id            TEXT          NOT NULL CONSTRAINT PK_agent_messages PRIMARY KEY,
  root_run_id   TEXT          NOT NULL
    CONSTRAINT FK_agent_messages_runs REFERENCES runs(id) ON DELETE CASCADE,
  from_run_id   TEXT          NOT NULL,
  from_agent    TEXT          NOT NULL,
  protocol      TEXT          NOT NULL,
  topic         TEXT          NOT NULL,
  content       TEXT          NOT NULL,
  reply_to      TEXT          NULL,
  created_at    TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_agent_messages_root ON agent_messages(root_run_id, created_at);

CREATE TABLE IF NOT EXISTS sync_sql_log (
  id           INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_sync_sql_log PRIMARY KEY,
  plan_id      TEXT          NULL,
  preview_id   TEXT          NULL,
  event_type   TEXT          NOT NULL,
  scope        TEXT          NULL,
  label        TEXT          NOT NULL,
  connection   TEXT          NOT NULL,
  sql_text     TEXT          NOT NULL,
  duration_ms  INT           NULL,
  row_count    INT           NULL,
  error        TEXT          NULL,
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_sync_sql_log_plan ON sync_sql_log(plan_id, id);

CREATE TABLE IF NOT EXISTS sync_environment_override_configs (
  name            TEXT          NOT NULL CONSTRAINT PK_sync_env_overrides PRIMARY KEY,
  overrides_json  TEXT          NOT NULL DEFAULT '{}',
  updated_at      TIMESTAMPTZ   NOT NULL,
  updated_by      TEXT          NULL
);

CREATE TABLE IF NOT EXISTS sync_catalog_versions (
  tenant_id      TEXT          NOT NULL,
  version        INT           NOT NULL,
  snapshot_json  TEXT          NOT NULL,
  reason         TEXT          NOT NULL,
  created_by     TEXT          NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL,
  CONSTRAINT PK_sync_catalog_versions PRIMARY KEY (tenant_id, version)
);

CREATE TABLE IF NOT EXISTS sync_catalog_active (
  tenant_id   TEXT          NOT NULL CONSTRAINT PK_sync_catalog_active PRIMARY KEY,
  version     INT           NOT NULL,
  updated_at  TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS scd2_strategy_active (
  tenant_id        TEXT          NOT NULL,
  id               TEXT          NOT NULL,
  current_version  INT           NOT NULL,
  retired_at       TIMESTAMPTZ   NULL,
  CONSTRAINT PK_scd2_strategy_active PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS scd2_strategy_versions (
  tenant_id    TEXT          NOT NULL,
  id           TEXT          NOT NULL,
  version      INT           NOT NULL,
  body_json    TEXT          NOT NULL,
  created_by   TEXT          NOT NULL,
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  reason       TEXT          NOT NULL DEFAULT '',
  CONSTRAINT PK_scd2_strategy_versions PRIMARY KEY (tenant_id, id, version)
);

CREATE TABLE IF NOT EXISTS approval_configs (
  tenant_id       TEXT          NOT NULL,
  target_env      TEXT          NOT NULL,
  risk_tier       TEXT          NOT NULL,
  policy          TEXT          NOT NULL,
  approvers_json  TEXT          NOT NULL DEFAULT '[]',
  bypass_role     TEXT          NULL,
  updated_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by      TEXT          NOT NULL,
  CONSTRAINT PK_approval_configs PRIMARY KEY (tenant_id, target_env, risk_tier)
);

CREATE TABLE IF NOT EXISTS notification_route_configs (
  id            TEXT          NOT NULL CONSTRAINT PK_notification_route_configs PRIMARY KEY,
  tenant_id     TEXT          NOT NULL,
  event_type    TEXT          NOT NULL,
  filter_json   TEXT          NOT NULL DEFAULT '{}',
  channel       TEXT          NOT NULL,
  target        TEXT          NOT NULL,
  enabled       INT           NOT NULL DEFAULT 1,
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by    TEXT          NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_notification_route_configs_ev
  ON notification_route_configs(tenant_id, event_type, enabled);

CREATE TABLE IF NOT EXISTS notification_log (
  id            INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_notification_log PRIMARY KEY,
  route_id      TEXT          NULL,
  event_type    TEXT          NOT NULL,
  channel       TEXT          NOT NULL,
  target        TEXT          NOT NULL,
  payload_json  TEXT          NOT NULL,
  status        TEXT          NOT NULL,
  attempts      INT           NOT NULL DEFAULT 0,
  last_error    TEXT          NULL,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  sent_at       TIMESTAMPTZ   NULL
);

CREATE TABLE IF NOT EXISTS freeze_window_configs (
  tenant_id     TEXT          NOT NULL,
  id            TEXT          NOT NULL,
  display_name  TEXT          NOT NULL,
  description   TEXT          NOT NULL DEFAULT '',
  starts_at     TIMESTAMPTZ   NOT NULL,
  ends_at       TIMESTAMPTZ   NOT NULL,
  created_by    TEXT          NOT NULL,
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT PK_freeze_window_configs PRIMARY KEY (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS proposer_schedule_configs (
  tenant_id    TEXT          NOT NULL,
  source       TEXT          NOT NULL,
  target       TEXT          NOT NULL,
  cron         TEXT          NOT NULL,
  enabled      INT           NOT NULL DEFAULT 1,
  last_run_at  TIMESTAMPTZ   NULL,
  next_run_at  TIMESTAMPTZ   NULL,
  updated_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by   TEXT          NOT NULL,
  CONSTRAINT PK_proposer_schedule_configs PRIMARY KEY (tenant_id, source, target)
);

CREATE TABLE IF NOT EXISTS notifications (
  id          TEXT          NOT NULL CONSTRAINT PK_notifications PRIMARY KEY,
  type        TEXT          NOT NULL,
  title       TEXT          NOT NULL,
  message     TEXT          NOT NULL,
  run_id      TEXT          NULL,
  step_id     TEXT          NULL,
  owner_upn   TEXT          NOT NULL
    CONSTRAINT FK_notifications_users REFERENCES users(upn),
  actions     TEXT          NOT NULL DEFAULT '[]',
  read        INT           NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_notifications_owner ON notifications(owner_upn, created_at DESC);

CREATE TABLE IF NOT EXISTS api_request_log (
  id                INT              NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_api_request_log PRIMARY KEY,
  method            TEXT             NOT NULL,
  url               TEXT             NOT NULL,
  status_code       INT              NOT NULL,
  duration_ms       DOUBLE PRECISION NOT NULL,
  request_body      TEXT             NULL,
  response_summary  TEXT             NULL,
  created_at        TIMESTAMPTZ      NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_drain_configs (
  id             TEXT          NOT NULL CONSTRAINT PK_webhook_drain_configs PRIMARY KEY,
  url            TEXT          NOT NULL,
  secret         TEXT          NOT NULL DEFAULT '',
  event_filters  TEXT          NOT NULL DEFAULT '[]',
  enabled        INT           NOT NULL DEFAULT 1,
  created_at     TIMESTAMPTZ   NOT NULL,
  updated_at     TIMESTAMPTZ   NOT NULL
);
`,

  6: `
CREATE TABLE IF NOT EXISTS proposer_runs (
  id            TEXT          NOT NULL CONSTRAINT PK_proposer_runs PRIMARY KEY,
  tenant_id     TEXT          NOT NULL,
  source        TEXT          NOT NULL,
  target        TEXT          NOT NULL,
  started_at    TIMESTAMPTZ   NOT NULL,
  finished_at   TIMESTAMPTZ   NULL,
  status        TEXT          NOT NULL,
  scanned       INT           NOT NULL DEFAULT 0,
  produced      INT           NOT NULL DEFAULT 0,
  errors        INT           NOT NULL DEFAULT 0,
  duration_ms   INT           NULL,
  triggered_by  TEXT          NOT NULL,
  trigger       TEXT          NOT NULL,
  error         TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_proposer_runs_pair
  ON proposer_runs(tenant_id, source, target, started_at DESC);

CREATE TABLE IF NOT EXISTS sync_proposals (
  id                     TEXT             NOT NULL CONSTRAINT PK_sync_proposals PRIMARY KEY,
  tenant_id              TEXT             NOT NULL,
  run_id                 TEXT             NOT NULL
    CONSTRAINT FK_sync_proposals_proposer_runs REFERENCES proposer_runs(id) ON DELETE CASCADE,
  fingerprint            TEXT             NOT NULL,
  source                 TEXT             NOT NULL,
  target                 TEXT             NOT NULL,
  entity_type            TEXT             NOT NULL,
  entity_id              TEXT             NOT NULL,
  entity_label           TEXT             NOT NULL,
  kind                   TEXT             NOT NULL,
  counts_json            TEXT             NOT NULL,
  detail_json            TEXT             NOT NULL,
  entity_def_version     INT              NULL,
  observed_at            TIMESTAMPTZ      NOT NULL,
  enqueued_at            TIMESTAMPTZ      NOT NULL DEFAULT NOW(),
  status                 TEXT             NOT NULL,
  annotation_json        TEXT             NULL,
  annotation_failed_open INT              NOT NULL DEFAULT 0,
  risk_tier              TEXT             NULL,
  risk_score             DOUBLE PRECISION NULL,
  rank_score             DOUBLE PRECISION NULL,
  plan_id                TEXT             NULL,
  snooze_until           TIMESTAMPTZ      NULL,
  superseded_by          TEXT             NULL,
  last_actor             TEXT             NULL,
  last_action            TEXT             NULL,
  last_action_at         TIMESTAMPTZ      NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_proposals_status ON sync_proposals(tenant_id, status, risk_tier);

CREATE TABLE IF NOT EXISTS sync_proposal_history (
  id             INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_sync_proposal_history PRIMARY KEY,
  proposal_id    TEXT          NOT NULL
    CONSTRAINT FK_sync_proposal_history_proposals REFERENCES sync_proposals(id) ON DELETE CASCADE,
  from_status    TEXT          NULL,
  to_status      TEXT          NOT NULL,
  actor          TEXT          NOT NULL,
  reason         TEXT          NOT NULL DEFAULT '',
  detail_json    TEXT          NOT NULL DEFAULT '{}',
  at             TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS IX_sync_proposal_history_pid ON sync_proposal_history(proposal_id, at DESC);

CREATE TABLE IF NOT EXISTS sync_approvals (
  id                   TEXT          NOT NULL CONSTRAINT PK_sync_approvals PRIMARY KEY,
  proposal_id          TEXT          NOT NULL
    CONSTRAINT FK_sync_approvals_proposals REFERENCES sync_proposals(id) ON DELETE CASCADE,
  tenant_id            TEXT          NOT NULL,
  requested_by         TEXT          NOT NULL,
  requested_at         TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  expires_at           TIMESTAMPTZ   NOT NULL,
  policy               TEXT          NOT NULL,
  state                TEXT          NOT NULL,
  granted_by_1         TEXT          NULL,
  granted_at_1         TIMESTAMPTZ   NULL,
  granted_by_2         TEXT          NULL,
  granted_at_2         TIMESTAMPTZ   NULL,
  rejected_by          TEXT          NULL,
  rejected_at          TIMESTAMPTZ   NULL,
  reject_reason        TEXT          NULL,
  bypass_by            TEXT          NULL,
  bypass_reason        TEXT          NULL,
  plan_id_at_request   TEXT          NULL,
  plan_hash_at_request TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_approvals_state ON sync_approvals(tenant_id, state, expires_at);

CREATE TABLE IF NOT EXISTS sync_approval_tokens (
  token_hash    TEXT          NOT NULL CONSTRAINT PK_sync_approval_tokens PRIMARY KEY,
  approval_id   TEXT          NOT NULL
    CONSTRAINT FK_sync_approval_tokens_approvals REFERENCES sync_approvals(id) ON DELETE CASCADE,
  action        TEXT          NOT NULL,
  issued_to     TEXT          NOT NULL,
  issued_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  expires_at    TIMESTAMPTZ   NOT NULL,
  used_at       TIMESTAMPTZ   NULL,
  used_by       TEXT          NULL
);
CREATE INDEX IF NOT EXISTS IX_sync_approval_tokens_app ON sync_approval_tokens(approval_id);

CREATE TABLE IF NOT EXISTS conversations (
  id            TEXT          NOT NULL CONSTRAINT PK_conversations PRIMARY KEY,
  channel_type  TEXT          NOT NULL,
  sender_id     TEXT          NOT NULL,
  sender_name   TEXT          NULL,
  active_run_id TEXT          NULL,
  thread_id     TEXT          NULL,
  created_at    TIMESTAMPTZ   NOT NULL,
  updated_at    TIMESTAMPTZ   NOT NULL,
  CONSTRAINT UQ_conversations_channel_sender UNIQUE (channel_type, sender_id)
);

CREATE TABLE IF NOT EXISTS outbound_messages (
  id              TEXT          NOT NULL CONSTRAINT PK_outbound_messages PRIMARY KEY,
  conversation_id TEXT          NOT NULL
    CONSTRAINT FK_outbound_messages_conversations REFERENCES conversations(id) ON DELETE CASCADE,
  channel_type    TEXT          NOT NULL,
  recipient_id    TEXT          NOT NULL,
  text            TEXT          NOT NULL,
  status          TEXT          NOT NULL DEFAULT 'queued',
  attempts        INT           NOT NULL DEFAULT 0,
  next_retry_at   TIMESTAMPTZ   NULL,
  last_error      TEXT          NULL,
  created_at      TIMESTAMPTZ   NOT NULL,
  delivered_at    TIMESTAMPTZ   NULL
);
CREATE INDEX IF NOT EXISTS IX_outbound_messages_status ON outbound_messages(status);

CREATE TABLE IF NOT EXISTS delivery_attempts (
  id             INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_delivery_attempts PRIMARY KEY,
  message_id     TEXT          NOT NULL
    CONSTRAINT FK_delivery_attempts_messages REFERENCES outbound_messages(id) ON DELETE CASCADE,
  attempt_number INT           NOT NULL,
  status         TEXT          NOT NULL,
  error          TEXT          NULL,
  duration_ms    INT           NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS channel_configs (
  type          TEXT          NOT NULL CONSTRAINT PK_channel_configs PRIMARY KEY,
  access_token  TEXT          NOT NULL,
  verify_token  TEXT          NOT NULL,
  app_secret    TEXT          NOT NULL,
  platform_id   TEXT          NOT NULL,
  created_at    TIMESTAMPTZ   NOT NULL,
  updated_at    TIMESTAMPTZ   NOT NULL
);

CREATE TABLE IF NOT EXISTS effects (
  id          TEXT          NOT NULL CONSTRAINT PK_effects PRIMARY KEY,
  run_id      TEXT          NOT NULL
    CONSTRAINT FK_effects_runs REFERENCES runs(id) ON DELETE CASCADE,
  seq         INT           NOT NULL DEFAULT 0,
  kind        TEXT          NOT NULL,
  tool        TEXT          NOT NULL,
  target      TEXT          NOT NULL,
  pre_hash    TEXT          NULL,
  post_hash   TEXT          NULL,
  status      TEXT          NOT NULL DEFAULT 'applied',
  metadata    TEXT          NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_effects_run ON effects(run_id, seq);

CREATE TABLE IF NOT EXISTS file_snapshots (
  id          TEXT          NOT NULL CONSTRAINT PK_file_snapshots PRIMARY KEY,
  effect_id   TEXT          NOT NULL
    CONSTRAINT FK_file_snapshots_effects REFERENCES effects(id) ON DELETE CASCADE,
  run_id      TEXT          NOT NULL,
  file_path   TEXT          NOT NULL,
  content     TEXT          NULL,
  hash        TEXT          NULL,
  file_mode   INT           NULL,
  created_at  TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_file_snapshots_run ON file_snapshots(run_id);
`,

  // Formerly created Playwright/browser tables — stack removed; drop in v11.
  7: `SELECT 1;`,

  11: `
DROP TABLE IF EXISTS browser_audit_log;
DROP TABLE IF EXISTS browser_domain_policy_configs;
DROP TABLE IF EXISTS browser_proxy_config;
DROP TABLE IF EXISTS browser_credentials;
DROP TABLE IF EXISTS browser_contexts;
`,

  12: `
ALTER TABLE runs DROP COLUMN IF EXISTS agent_id;
`,

  8: `
CREATE TABLE IF NOT EXISTS eval_dataset_entries (
  id             TEXT          NOT NULL CONSTRAINT PK_eval_dataset_entries PRIMARY KEY,
  thread_id      TEXT          NULL,
  run_id         TEXT          NOT NULL,
  scope_id       TEXT          NOT NULL,
  kind           TEXT          NOT NULL,
  call_index     INT           NULL,
  label          TEXT          NULL,
  input_json     TEXT          NOT NULL,
  output_json    TEXT          NULL,
  metadata_json  TEXT          NULL,
  created_by     TEXT          NOT NULL,
  created_at     TIMESTAMPTZ   NOT NULL
);
CREATE INDEX IF NOT EXISTS IX_eval_dataset_run ON eval_dataset_entries(run_id);
CREATE INDEX IF NOT EXISTS IX_eval_dataset_thread ON eval_dataset_entries(thread_id);
CREATE INDEX IF NOT EXISTS IX_eval_dataset_created ON eval_dataset_entries(created_at DESC);
`,

  9: `
CREATE TABLE IF NOT EXISTS memory_entries (
  id            TEXT             NOT NULL CONSTRAINT PK_memory_entries PRIMARY KEY,
  tier          TEXT             NOT NULL,
  role          TEXT             NOT NULL DEFAULT 'assistant',
  content       TEXT             NOT NULL,
  metadata      TEXT             NOT NULL DEFAULT '{}',
  source        TEXT             NOT NULL DEFAULT 'agent',
  confidence    DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  salience      DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  access_count  INT              NOT NULL DEFAULT 0,
  run_id        TEXT             NULL
    CONSTRAINT FK_memory_entries_runs REFERENCES runs(id) ON DELETE SET NULL,
  parent_id     TEXT             NULL,
  upn           TEXT             NULL,
  shared        INT              NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ      NOT NULL,
  updated_at    TIMESTAMPTZ      NOT NULL,
  CONSTRAINT CK_memory_entries_tier CHECK (tier IN ('working', 'episodic', 'semantic')),
  CONSTRAINT CK_memory_entries_role CHECK (role IN ('user', 'assistant', 'tool', 'system', 'summary')),
  CONSTRAINT CK_memory_entries_source CHECK (source IN ('system', 'tool', 'user', 'agent', 'external'))
);
CREATE INDEX IF NOT EXISTS IX_me_tier ON memory_entries(tier);
CREATE INDEX IF NOT EXISTS IX_me_run ON memory_entries(run_id);
CREATE INDEX IF NOT EXISTS IX_me_created ON memory_entries(created_at);
CREATE INDEX IF NOT EXISTS IX_me_upn ON memory_entries(upn);
CREATE INDEX IF NOT EXISTS IX_me_shared ON memory_entries(shared);

CREATE TABLE IF NOT EXISTS memory_vectors (
  entry_id   TEXT          NOT NULL CONSTRAINT PK_memory_vectors PRIMARY KEY
    CONSTRAINT FK_memory_vectors_entries REFERENCES memory_entries(id) ON DELETE CASCADE,
  embedding  BYTEA         NOT NULL,
  dimension  INT           NOT NULL,
  upn        TEXT          NULL,
  shared     INT           NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS IX_mv_upn ON memory_vectors(upn);
CREATE INDEX IF NOT EXISTS IX_mv_shared ON memory_vectors(shared);

CREATE TABLE IF NOT EXISTS tool_knowledge_cache (
  id              INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_tool_knowledge_cache PRIMARY KEY,
  tool            TEXT          NOT NULL,
  qname           TEXT          NOT NULL,
  mode            TEXT          NOT NULL DEFAULT '',
  connection      TEXT          NOT NULL DEFAULT 'default',
  payload_text    TEXT          NOT NULL,
  fingerprint     TEXT          NOT NULL,
  bytes           INT           NOT NULL,
  created_by_upn  TEXT          NULL,
  created_at      BIGINT        NOT NULL,
  last_hit_at     BIGINT        NULL,
  hit_count       INT           NOT NULL DEFAULT 0,
  CONSTRAINT UQ_tool_knowledge_cache UNIQUE (tool, qname, mode, connection)
);
CREATE INDEX IF NOT EXISTS IX_tk_lookup ON tool_knowledge_cache(tool, qname);
CREATE INDEX IF NOT EXISTS IX_tk_created ON tool_knowledge_cache(created_at);

CREATE TABLE IF NOT EXISTS resolved_terms_cache (
  id              INT           NOT NULL GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_resolved_terms_cache PRIMARY KEY,
  term            TEXT          NOT NULL,
  qname           TEXT          NOT NULL,
  connection      TEXT          NOT NULL DEFAULT 'default',
  created_by_upn  TEXT          NULL,
  created_at      BIGINT        NOT NULL,
  last_hit_at     BIGINT        NULL,
  hit_count       INT           NOT NULL DEFAULT 0,
  CONSTRAINT UQ_resolved_terms_cache UNIQUE (term, qname, connection)
);
CREATE INDEX IF NOT EXISTS IX_rt_term ON resolved_terms_cache(term);
CREATE INDEX IF NOT EXISTS IX_rt_conn ON resolved_terms_cache(connection);
CREATE INDEX IF NOT EXISTS IX_rt_created ON resolved_terms_cache(created_at DESC);
`,

  10: `
ALTER TABLE memory_entries ADD COLUMN IF NOT EXISTS search_vector tsvector;

CREATE OR REPLACE FUNCTION mia_memory_entries_search_vector_update()
RETURNS trigger AS $$
BEGIN
  NEW.search_vector := to_tsvector(
    'simple',
    coalesce(NEW.content, '') || ' ' || coalesce(NEW.metadata, '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_memory_entries_search_vector ON memory_entries;
CREATE TRIGGER trg_memory_entries_search_vector
  BEFORE INSERT OR UPDATE OF content, metadata
  ON memory_entries
  FOR EACH ROW
  EXECUTE PROCEDURE mia_memory_entries_search_vector_update();

UPDATE memory_entries
SET search_vector = to_tsvector(
  'simple',
  coalesce(content, '') || ' ' || coalesce(metadata, '')
)
WHERE search_vector IS NULL;

CREATE INDEX IF NOT EXISTS IX_me_search_vector ON memory_entries USING GIN (search_vector);
`,

  13: `
ALTER TABLE run_tool_approvals
  ADD COLUMN IF NOT EXISTS grant_scope TEXT NOT NULL DEFAULT 'instance';
`,
}
