/**
 * F1.8 — Minimal PDF renderer for evidence envelopes.
 *
 * We avoid heavy third-party deps. The PDF is a deliberately simple,
 * single-page-per-section text PDF generated by hand following the
 * PDF 1.4 spec. It is enough to print, archive, and email to auditors
 * — not a typesetting product.
 *
 * Layout:
 *   page 1: Cover (envelope header, signature info)
 *   page 2: Proposal summary
 *   page 3: Annotation
 *   page 4: Plan totals (one row per table)
 *   page 5: Approval trail (if present)
 *   page 6: Execution + verification summary
 *   page 7: Audit history
 *
 * The PDF intentionally embeds the canonical-JSON envelope hash and
 * the signature so the printout is forensically tied to the JSON file.
 */

import type { EvidenceEnvelope } from "./envelope.js"

interface Page {
  title: string
  lines: readonly string[]
}

export function renderEvidencePdf(env: EvidenceEnvelope): Buffer {
  const pages = buildPages(env)
  return buildPdfBytes(pages)
}

function buildPages(env: EvidenceEnvelope): Page[] {
  return [
    {
      title: "Sync Evidence — Cover",
      lines: [
        `Evidence ID:   ${env.envelope.id}`,
        `Created at:    ${env.envelope.createdAt}`,
        `Tenant:        ${env.envelope.tenantId}`,
        `Plan ID:       ${env.envelope.planId}`,
        `Proposal ID:   ${env.envelope.proposalId ?? "(direct execution)"}`,
        `Env-pair:      ${env.envelope.envPair.source} -> ${env.envelope.envPair.target}`,
        `Actor:         ${env.envelope.actor}`,
        `Outcome:       ${env.envelope.outcome}`,
        ``,
        `Signature alg: ${env.signature?.alg ?? "(unsigned)"}`,
        `Signer ID:     ${env.signature?.signerId ?? "-"}`,
        `Content hash:  ${env.signature?.contentHash ?? "-"}`,
        ``,
        `--- Hash chain (one per section) ---`,
        ...env.hashChain.map((h, i) => `${String(i + 1).padStart(2, " ")}. ${h}`)
      ]
    },
    section("Proposal", env.proposal),
    section("Annotation", env.annotation),
    section("Plan", env.plan),
    section("Approval", env.approval),
    section("Execution", env.execution),
    section("Verification", env.verification),
    {
      title: "Audit",
      lines: env.audit.map((row, i) => `${i + 1}. ${oneLine(row)}`)
    }
  ]
}

function section(title: string, body: unknown): Page {
  if (body === null || body === undefined) {
    return { title, lines: [`(no ${title.toLowerCase()} attached)`] }
  }
  // pretty-print, wrap at 100 cols
  const raw = JSON.stringify(body, null, 2).split("\n")
  return { title, lines: raw.flatMap((l) => wrap(l, 100)) }
}

function wrap(line: string, w: number): string[] {
  if (line.length <= w) return [line]
  const out: string[] = []
  for (let i = 0; i < line.length; i += w) out.push(line.slice(i, i + w))
  return out
}

function oneLine(v: unknown): string {
  const s = typeof v === "string" ? v : JSON.stringify(v)
  return s.length > 200 ? s.slice(0, 200) + "…" : s
}

// ── primitive PDF writer ─────────────────────────────────────────
// Produces a valid PDF 1.4 with embedded Helvetica. Each page is a
// single text content stream with line-by-line `Tj` showings. No
// fonts other than Helvetica, no images. Output is deterministic.

function buildPdfBytes(pages: readonly Page[]): Buffer {
  const objects: string[] = []
  const xref: number[] = []

  // 1: Catalog
  objects.push("<< /Type /Catalog /Pages 2 0 R >>")
  // 2: Pages (filled in after we know page count + ids)
  const pageObjStart = 4
  const pageIds = pages.map((_, i) => pageObjStart + i * 2)
  objects.push(
    `<< /Type /Pages /Count ${pages.length} /Kids [${pageIds.map((id) => `${id} 0 R`).join(" ")}] >>`
  )
  // 3: Font
  objects.push("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>")

  for (let i = 0; i < pages.length; i++) {
    const pageId = pageIds[i]!
    const contentId = pageId + 1
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`
    )
    objects.push(buildContentObject(pages[i]!))
  }

  // assemble PDF
  let body = "%PDF-1.4\n%\u00E2\u00E3\u00CF\u00D3\n"
  for (let i = 0; i < objects.length; i++) {
    xref.push(Buffer.byteLength(body, "binary"))
    body += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`
  }
  const xrefOffset = Buffer.byteLength(body, "binary")
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of xref) body += `${String(off).padStart(10, "0")} 00000 n \n`
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return Buffer.from(body, "binary")
}

function buildContentObject(page: Page): string {
  const title = escapePdfString(page.title)
  let stream = ""
  stream += "BT\n/F1 14 Tf\n72 760 Td\n"
  stream += `(${title}) Tj\n`
  stream += "/F1 9 Tf\n"
  stream += "0 -22 Td\n"
  for (const line of page.lines.slice(0, 80)) {
    stream += `(${escapePdfString(line)}) Tj\n0 -11 Td\n`
  }
  stream += "ET\n"
  return `<< /Length ${Buffer.byteLength(stream, "binary")} >>\nstream\n${stream}endstream`
}

function escapePdfString(s: string): string {
  return (
    s
      .replace(/\\/g, "\\\\")
      .replace(/\(/g, "\\(")
      .replace(/\)/g, "\\)")
      // strip control chars except tab
      .replace(/[\x00-\x08\x0B-\x1F\x7F]/g, "")
  )
}
